// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0edWrOa16M758ovO9ptN4T7rfBF2ojdM',
    appId: '1:356395379948:web:bc5b6d3ae10fe229a549c9',
    messagingSenderId: '356395379948',
    projectId: 'digit-recognizer-8d4f0',
    authDomain: 'digit-recognizer-8d4f0.firebaseapp.com',
    storageBucket: 'digit-recognizer-8d4f0.appspot.com',
    measurementId: 'G-TMSLE8TL1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCln3FHQXHWl4RaSGPsqxi0fd8usapCs',
    appId: '1:356395379948:android:a505a1ca1fdadb26a549c9',
    messagingSenderId: '356395379948',
    projectId: 'digit-recognizer-8d4f0',
    storageBucket: 'digit-recognizer-8d4f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpyrJHHiwpa6HSMlpQ3drDLlQa_WpY4rg',
    appId: '1:356395379948:ios:c3ee0b47178c5504a549c9',
    messagingSenderId: '356395379948',
    projectId: 'digit-recognizer-8d4f0',
    storageBucket: 'digit-recognizer-8d4f0.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpyrJHHiwpa6HSMlpQ3drDLlQa_WpY4rg',
    appId: '1:356395379948:ios:6bcdd6f19bc839dba549c9',
    messagingSenderId: '356395379948',
    projectId: 'digit-recognizer-8d4f0',
    storageBucket: 'digit-recognizer-8d4f0.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
